version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-casamento
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - casamento-net

  redis:
    image: redis:7
    container_name: redis-casamento
    ports:
      - "6379:6379"
    networks:
      - casamento-net


  evolution-api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution-api
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "${EVOLUTION_PORT}:8080"
    environment:
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      AUTHENTICATION_API_KEY: ${AUTHENTICATION_API_KEY}
      DATABASE_PROVIDER: ${DATABASE_PROVIDER}
      DATABASE_URL: ${DATABASE_URL}
      CACHE_REDIS_URI: ${REDIS_URI}
    networks:
      - casamento-net

  casamento-api:
    build: .
    container_name: casamento-api
    restart: always
    depends_on:
      - postgres
      - evolution-api
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-casamento:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EVOLUTION_API_BASE_URL: http://evolution-api:8080
    networks:
      - casamento-net

volumes:
  postgres_data:

networks:
  casamento-net:
    driver: bridge
